### ISSUE TITLE
Doesn't build: no `intern` in `parse::token`

### ISSUE THREAD

**Issue by joelonsql** [thehydroimpulse/postgres-extension.rs#12]
Trying to build using rustc 1.16.0-nightly (47c8d9fdc 2017-01-08), but it fails:

error[E0432]: unresolved import `syntax::parse::token::intern`
  --> /Users/joel/src/postgres-extension.rs/macros/src/lib.rs:11:5
   |
11 | use syntax::parse::token::intern;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `intern` in `parse::token`

error[E0432]: unresolved import `syntax::parse::token::InternedString`
  --> /Users/joel/src/postgres-extension.rs/macros/src/lib.rs:21:5
   |
21 | use syntax::parse::token::InternedString;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `InternedString` in `parse::token`

error: aborting due to 2 previous errors

error: Could not compile `postgres_extension_macros`.

**Comment by toplinuxsir** [comment]
try to build with rustc 1.30 stable :+1: 
: unresolved import `syntax::parse::token::intern`
